server:
  port: 8765

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

spring:
  application:
      name: dfjinxin-gateway
  redis:
      database: 0 # Redis数据库索引（默认为0）
      host: localhost # Redis服务器地址
      port: 6379  # Redis服务器连接端口
      password: # Redis服务器连接密码（默认为空）
      lettuce:
        pool:
          maxActive: 300 # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 100 # 连接池中的最大空闲连接
          min-idle: 0 # 连接池中的最小空闲连接
  sleuth:
    enabled: true
    http:
      legacy:
        enabled: true
  cloud:
     gateway:
       discovery:
         locator:
           lowerCaseServiceId: true
           enabled: true
       routes:
        # =====================================
        - id: dfjinxin-sys
          uri: lb://dfjinxin-fast
          order: 8000
          predicates:
          - Path=/api/sys/**
          filters:
          - StripPrefix=1
        - id: dfjinxin-job
          uri: lb://dfjinxin-fast
          order: 8001
          predicates:
          - Path=/api/job/**
          filters:
          - StripPrefix=1
        - id: dfjinxin-oss
          uri: lb://dfjinxin-fast
          order: 8001
          predicates:
          - Path=/api/oss/**
          filters:
          - StripPrefix=1
     nacos:
        discovery:
          server-addr: 127.0.0.1:8848
     sentinel:
        transport:
          dashboard: localhost:8080
  zipkin:
      base-url: http://192.168.99.100:9411

logging:
  level:
    com.dfjinxin.gate.v2: info

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false


gate:
  ignore:
    startWith: /sys/jwt


auth:
  serviceId: dfjinxin-auth
  user:
    token-header: Authorization
  client:
    token-header: x-client-token
    id: dfjinxin-gate  #不填则默认读取spring.application.name
    secret: 123456
  permission:
    allow: false


ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

admin:
  application:
    name: dfjinxin-fast

jwt:
  token-header: Authorization
  expire: 14400
  rsa-secret: xx1WET12^%3^(WE45